# Generated by Django 3.2.11 on 2022-01-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0004_auto_20220130_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='date',
            field=models.DateField(default='2022-01-30'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetup',
            name='organizeer_email',
            field=models.EmailField(default='2022-01-04', max_length=254),
            preserve_default=False,
        ),
    ]
